# Generated by Django 4.2.5 on 2023-09-19 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('fechalnicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('descripcion', models.TextField()),
                ('image_url', models.URLField()),
                ('videos', models.URLField()),
                ('precio', models.FloatField()),
                ('capacidad', models.IntegerField()),
                ('asistencia', models.IntegerField()),
                ('categorias', models.CharField(max_length=255)),
                ('etiquetas', models.CharField(max_length=255)),
                ('esRecurrente', models.BooleanField()),
                ('calificacion', models.FloatField()),
                ('esDestacado', models.BooleanField()),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reservas', models.ManyToManyField(related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
