# Generated by Django 4.2.5 on 2023-09-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='fechalnicio',
            new_name='fechaInicio',
        ),
    ]
