# Generated by Django 4.2.7 on 2023-11-18 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_rename_fechalnicio_evento_fechainicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
    ]
