# Generated by Django 4.2.7 on 2023-11-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_remove_evento_esdestacado_remove_evento_esrecurrente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='image_url',
        ),
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
