# Generated by Django 4.2.7 on 2023-11-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_remove_evento_image_url_evento_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='asistencia',
            field=models.IntegerField(default=0),
        ),
    ]
