# Generated by Django 4.2.7 on 2023-11-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_alter_evento_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='calificacion',
            field=models.IntegerField(default=0),
        ),
    ]
