# Generated by Django 4.2.7 on 2023-11-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0010_alter_evento_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pagina/static/pagina/event_images/'),
        ),
    ]
