# Generated by Django 4.2.7 on 2023-11-20 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0012_alter_evento_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='reservas',
        ),
    ]
