# Generated by Django 4.2.7 on 2023-11-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0013_remove_evento_reservas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pagina/static/pagina/event_images/'),
        ),
    ]
